baseURL = 'https://mu-tsing.github.io/'
languageCode = 'en-us'
title = "Mu-Tsing's Website"

theme = ["hugo-embed-pdf-shortcode", "hugo-book"]
enableInlineShortcodes = true

publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
          
[params]
  math = true