[en]
  languageName = "English"
  contentDir = 'content/en'
  weight = 1


[zh]
  languageName = "简体中文"
  contentDir = 'content/zh'
  weight = 2

# [zh-hant]
#   languageName = "繁體中文"
#   weight = 3
#   [zh-hant.params]
#     description = "一個快速、響應式和功能豐富的 Hugo 博客主題"
#     keywords = "Hugo, Bootstrap, 博客主題"
#     [zh-hant.params.archive]
#       dateFormat = "01-02"

# [ja]
#   languageName = "日本語"
#   weight = 6
#   [ja.params]
#     description = "Hugo向けにカスタマイズされた非常に高速で応答性の高い、機能豊富なブログテーマ"
#     keywords = "Hugo, Bootstrap, ブログテーマ"
#     [ja.params.archive]
#       dateFormat = "1/2"